// ======================================================================
// \title  BufferLogger_LogStateEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for BufferLogger_LogState enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Svc/BufferLogger/BufferLogger_LogStateEnumAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  BufferLogger_LogState& BufferLogger_LogState ::
    operator=(const BufferLogger_LogState& obj)
  {
    this->e = obj.e;
    return *this;
  }

  BufferLogger_LogState& BufferLogger_LogState ::
    operator=(T e)
  {
    this->e = e;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const BufferLogger_LogState& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool BufferLogger_LogState ::
    isValid() const
  {
    return ((e >= LOGGING_ON) && (e <= LOGGING_OFF));
  }

  Fw::SerializeStatus BufferLogger_LogState ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus BufferLogger_LogState ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING || BUILD_UT

  void BufferLogger_LogState ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case LOGGING_ON:
        s = "LOGGING_ON";
        break;
      case LOGGING_OFF:
        s = "LOGGING_OFF";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%d)", s.toChar(), e);
  }

#endif

}
