// ======================================================================
// \title  BurnwireTesterTopologyAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for BurnwireTester topology
// ======================================================================

#ifndef BurnwireTester_BurnwireTesterTopologyAc_HPP
#define BurnwireTester_BurnwireTesterTopologyAc_HPP

#include "BurnwireTester/Top/BurnwireTesterTopologyDefs.hpp"
#include "Components/Burnwire/Burnwire.hpp"
#include "Drv/BlockDriver/BlockDriver.hpp"
#include "Drv/LinuxGpioDriver/LinuxGpioDriver.hpp"
#include "Drv/TcpClient/TcpClient.hpp"
#include "Svc/ActiveLogger/ActiveLogger.hpp"
#include "Svc/ActiveRateGroup/ActiveRateGroup.hpp"
#include "Svc/AssertFatalAdapter/AssertFatalAdapter.hpp"
#include "Svc/BufferManager/BufferManager.hpp"
#include "Svc/CmdDispatcher/CommandDispatcher.hpp"
#include "Svc/CmdSequencer/CmdSequencer.hpp"
#include "Svc/Deframer/Deframer.hpp"
#include "Svc/FatalHandler/FatalHandler.hpp"
#include "Svc/FileDownlink/FileDownlink.hpp"
#include "Svc/FileManager/FileManager.hpp"
#include "Svc/FileUplink/FileUplink.hpp"
#include "Svc/Framer/Framer.hpp"
#include "Svc/Health/Health.hpp"
#include "Svc/LinuxTime/LinuxTime.hpp"
#include "Svc/PassiveConsoleTextLogger/PassiveTextLogger.hpp"
#include "Svc/PrmDb/PrmDb.hpp"
#include "Svc/RateGroupDriver/RateGroupDriver.hpp"
#include "Svc/StaticMemory/StaticMemory.hpp"
#include "Svc/SystemResources/SystemResources.hpp"
#include "Svc/TlmChan/TlmChan.hpp"

namespace BurnwireTester {

  // ----------------------------------------------------------------------
  // Constants
  // ----------------------------------------------------------------------

  namespace BaseIds {
    enum {
      blockDrv = 0x100,
      rateGroup1 = 0x200,
      rateGroup2 = 0x300,
      rateGroup3 = 0x400,
      cmdDisp = 0x500,
      cmdSeq = 0x600,
      fileDownlink = 0x700,
      fileManager = 0x800,
      fileUplink = 0x900,
      eventLogger = 0xB00,
      tlmSend = 0xC00,
      prmDb = 0xD00,
      burnwire = 0xE00,
      health = 0x2000,
      comm = 0x4000,
      downlink = 0x4100,
      fatalAdapter = 0x4200,
      fatalHandler = 0x4300,
      fileUplinkBufferManager = 0x4400,
      linuxTime = 0x4500,
      rateGroupDriver = 0x4600,
      staticMemory = 0x4700,
      textLogger = 0x4800,
      uplink = 0x4900,
      systemResources = 0x4A00,
      gpioDriver = 0x4C00,
    };
  }

  namespace InstanceIds {
    enum {
      blockDrv,
      burnwire,
      cmdDisp,
      cmdSeq,
      comm,
      downlink,
      eventLogger,
      fatalAdapter,
      fatalHandler,
      fileDownlink,
      fileManager,
      fileUplink,
      fileUplinkBufferManager,
      gpioDriver,
      health,
      linuxTime,
      prmDb,
      rateGroup1,
      rateGroup2,
      rateGroup3,
      rateGroupDriver,
      staticMemory,
      systemResources,
      textLogger,
      tlmSend,
      uplink,
    };
  }

  namespace Priorities {
    enum {
      blockDrv = 140,
      burnwire = 95,
      cmdDisp = 101,
      cmdSeq = 100,
      eventLogger = 98,
      fileDownlink = 100,
      fileManager = 100,
      fileUplink = 100,
      prmDb = 96,
      rateGroup1 = 120,
      rateGroup2 = 119,
      rateGroup3 = 118,
      tlmSend = 97,
    };
  }

  namespace QueueSizes {
    enum {
      blockDrv = 10,
      burnwire = 10,
      cmdDisp = 20,
      cmdSeq = 10,
      eventLogger = 10,
      fileDownlink = 30,
      fileManager = 30,
      fileUplink = 30,
      health = 25,
      prmDb = 10,
      rateGroup1 = 10,
      rateGroup2 = 10,
      rateGroup3 = 10,
      tlmSend = 10,
    };
  }

  namespace StackSizes {
    enum {
      blockDrv = 65536,
      burnwire = 65536,
      cmdDisp = 65536,
      cmdSeq = 65536,
      eventLogger = 65536,
      fileDownlink = 65536,
      fileManager = 65536,
      fileUplink = 65536,
      prmDb = 65536,
      rateGroup1 = 65536,
      rateGroup2 = 65536,
      rateGroup3 = 65536,
      tlmSend = 65536,
    };
  }

  namespace TaskIds {
    enum {
      blockDrv,
      burnwire,
      cmdDisp,
      cmdSeq,
      eventLogger,
      fileDownlink,
      fileManager,
      fileUplink,
      prmDb,
      rateGroup1,
      rateGroup2,
      rateGroup3,
      tlmSend,
    };
  }

  // ----------------------------------------------------------------------
  // Component instances
  // ----------------------------------------------------------------------

  //! blockDrv
  extern Drv::BlockDriver blockDrv;

  //! burnwire
  extern Components::Burnwire burnwire;

  //! cmdDisp
  extern Svc::CommandDispatcher cmdDisp;

  //! cmdSeq
  extern Svc::CmdSequencer cmdSeq;

  //! comm
  extern Drv::TcpClient comm;

  //! downlink
  extern Svc::Framer downlink;

  //! eventLogger
  extern Svc::ActiveLogger eventLogger;

  //! fatalAdapter
  extern Svc::AssertFatalAdapter fatalAdapter;

  //! fatalHandler
  extern Svc::FatalHandler fatalHandler;

  //! fileDownlink
  extern Svc::FileDownlink fileDownlink;

  //! fileManager
  extern Svc::FileManager fileManager;

  //! fileUplink
  extern Svc::FileUplink fileUplink;

  //! fileUplinkBufferManager
  extern Svc::BufferManager fileUplinkBufferManager;

  //! gpioDriver
  extern Drv::LinuxGpioDriver gpioDriver;

  //! health
  extern Svc::Health health;

  //! linuxTime
  extern Svc::LinuxTime linuxTime;

  //! prmDb
  extern Svc::PrmDb prmDb;

  //! rateGroup1
  extern Svc::ActiveRateGroup rateGroup1;

  //! rateGroup2
  extern Svc::ActiveRateGroup rateGroup2;

  //! rateGroup3
  extern Svc::ActiveRateGroup rateGroup3;

  //! rateGroupDriver
  extern Svc::RateGroupDriver rateGroupDriver;

  //! staticMemory
  extern Svc::StaticMemory staticMemory;

  //! systemResources
  extern Svc::SystemResources systemResources;

  //! textLogger
  extern Svc::PassiveTextLogger textLogger;

  //! tlmSend
  extern Svc::TlmChan tlmSend;

  //! uplink
  extern Svc::Deframer uplink;

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  //! Initialize components
  void initComponents(
      const TopologyState& state //!< The topology state
  );

  //! Set component base Ids
  void setBaseIds();

  //! Connect components
  void connectComponents();

  //! Register commands
  void regCommands();

  //! Start tasks
  void startTasks(
      const TopologyState& state //!< The topology state
  );

  //! Stop tasks
  void stopTasks(
      const TopologyState& state //!< The topology state
  );

  //! Free threads
  void freeThreads(
      const TopologyState& state //!< The topology state
  );

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  //! Set up the topology
  void setup(
      const TopologyState& state //!< The topology state
  );

  //! Tear down the topology
  void teardown(
      const TopologyState& state //!< The topology state
  );

}

#endif
