// ======================================================================
// \title  I2cWriteReadPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for I2cWriteRead port
// ======================================================================

#include "F-Prime/Drv/I2cDriverPorts/I2cWriteReadPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/StringUtils.hpp"

namespace Drv {

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputI2cWriteReadPort ::
    InputI2cWriteReadPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputI2cWriteReadPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputI2cWriteReadPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  Drv::I2cStatus InputI2cWriteReadPort ::
    invoke(
        U32 addr,
        Fw::Buffer& writeBuffer,
        Fw::Buffer& readBuffer
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, addr, writeBuffer, readBuffer);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputI2cWriteReadPort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    // For ports with a return type, invokeSerial is not used
    (void) _buffer;

    FW_ASSERT(0);
    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputI2cWriteReadPort ::
    OutputI2cWriteReadPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputI2cWriteReadPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputI2cWriteReadPort ::
    addCallPort(InputI2cWriteReadPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  Drv::I2cStatus OutputI2cWriteReadPort ::
    invoke(
        U32 addr,
        Fw::Buffer& writeBuffer,
        Fw::Buffer& readBuffer
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_port != nullptr);
    return this->m_port->invoke(addr, writeBuffer, readBuffer);
  }

}
