// ======================================================================
// \title  PolyPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Poly port
// ======================================================================

#ifndef Svc_PolyPortAc_HPP
#define Svc_PolyPortAc_HPP

#include <cstdio>
#include <cstring>

#include "FpConfig.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Time/Time.hpp"
#include "Fw/Types/PolyType.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/StringType.hpp"
#include "Svc/PolyIf/MeasurementStatusEnumAc.hpp"

namespace Svc {

  //! Input Poly port
  //! Port for setting and getting PolyType values
  class InputPolyPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          sizeof(U32) +
          Svc::MeasurementStatus::SERIALIZED_SIZE +
          Fw::Time::SERIALIZED_SIZE +
          Fw::PolyType::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef void (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        NATIVE_INT_TYPE portNum,
        U32 entry,
        Svc::MeasurementStatus& status,
        Fw::Time& time,
        Fw::PolyType& val
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputPolyPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      void invoke(
          U32 entry, //!< The entry to access
          Svc::MeasurementStatus& status, //!< The command response argument
          Fw::Time& time, //!< The time of the measurement
          Fw::PolyType& val //!< The value to be passed
      );

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output Poly port
  //! Port for setting and getting PolyType values
  class OutputPolyPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputPolyPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputPolyPort* callPort //!< The input port
      );

      //! Invoke a port interface
      void invoke(
          U32 entry, //!< The entry to access
          Svc::MeasurementStatus& status, //!< The command response argument
          Fw::Time& time, //!< The time of the measurement
          Fw::PolyType& val //!< The value to be passed
      );

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputPolyPort* m_port;

  };

}

#endif
